Repository uiters/lalastay, pull requests merged in 2019-12, with the labels that each got.

#25 Add withLayout HOC
  src/common/router.js
  src/components/BasicLayout.js
  src/components/index.js
  src/components/withLayout.js
  src/routes/CompareHomestay/index.js
  src/routes/Home/index.js
  src/routes/HomeByArea/index.js
  src/routes/HomeDetail/index.js
  src/routes/NotFound/index.js
  src/routes/Payment/index.js
  src/routes/Payment/style.css
  src/routes/RepoDetail/index.js
  src/routes/Repos/index.js
  src/routes/index.js
Labels: new feature

#30 Setup global font
  src/index.css
  src/routes/Payment/style.css
Labels: new feature

#36 Complete Invoice screen
  src/common/router.js
  src/index.css
  src/routes/Invoice/components/Breadcrumb.js
  src/routes/Invoice/index.js
  src/routes/Invoice/style.css
  src/routes/index.js
Labels: new feature

#37 Add time for comment
  src/components/BodyHomeDetail/index.js
  src/components/Navbar/index.js
  src/components/comment/index.js
  src/components/comment/style.css
Labels: new feature

#38 Fix bug 🐛: class name is override
  src/routes/Invoice/index.js
  src/routes/Invoice/style.css
Labels: new feature

#40 Fix versions bug
  package.json
  yarn.lock
Labels: bug

#47 🦄 Responsive for Payment page
  src/routes/Invoice/style.css
  src/routes/Payment/index.js
  src/routes/Payment/style.css
Labels: new feature

#48 🐹 Apply Sarabun font
  public/index.html
  src/components/Navbar/index.js
  src/index.css
  src/routes/CompareHomestay/style.css
  src/routes/Home/index.js
  src/routes/Login/style.css
  src/routes/NotFound/style.css
Labels: new feature

#56 Comment component
  package.json
  public/index.html
  src/components/BodyHomeDetail/index.js
  src/config/index.js
  src/routes/HomeDetail/components/Comment.js
  src/routes/HomeDetail/components/CommentHeader.js
  src/routes/HomeDetail/components/CommentInput.js
  src/routes/HomeDetail/components/Comments.js
  src/routes/HomeDetail/components/Input.js
  src/routes/Invoice/style.css
  src/routes/Payment/style.css
  yarn.lock
Labels: new feature

#57 🐦 Handle responsive for Invoice page
  src/routes/Invoice/index.js
  src/routes/Invoice/style.css
Labels: enhancement

#58 Update README.md
  README.md
Labels: documentation
